<template>
  <section id="section-pallette" style="display:none;">
    <header>
      <button type="button">닫기</button>
    </header>
    <main>
      <ul>
        <li data-value="#f8f9fa" style="background-color:#f8f9fa"></li>
        <li data-value="#f1f3f5" style="background-color:#f1f3f5"></li>
        <li data-value="#e9ecef" style="background-color:#e9ecef"></li>
        <li data-value="#dee2e6" style="background-color:#dee2e6"></li>
        <li data-value="#ced4da" style="background-color:#ced4da"></li>
        <li data-value="#adb5bd" style="background-color:#adb5bd"></li>
        <li data-value="#868e96" style="background-color:#868e96"></li>
        <li data-value="#495057" style="background-color:#495057"></li>
        <li data-value="#343a40" style="background-color:#343a40"></li>
        <li data-value="#212529" style="background-color:#212529"></li>
        <li data-value="#fff5f5" style="background-color:#fff5f5"></li>
        <li data-value="#ffe3e3" style="background-color:#ffe3e3"></li>
        <li data-value="#ffc9c9" style="background-color:#ffc9c9"></li>
        <li data-value="#ffa8a8" style="background-color:#ffa8a8"></li>
        <li data-value="#ff8787" style="background-color:#ff8787"></li>
        <li data-value="#ff6b6b" style="background-color:#ff6b6b"></li>
        <li data-value="#fa5252" style="background-color:#fa5252"></li>
        <li data-value="#f03e3e" style="background-color:#f03e3e"></li>
        <li data-value="#e03131" style="background-color:#e03131"></li>
        <li data-value="#c92a2a" style="background-color:#c92a2a"></li>
        <li data-value="#fff0f6" style="background-color:#fff0f6"></li>
        <li data-value="#ffdeeb" style="background-color:#ffdeeb"></li>
        <li data-value="#fcc2d7" style="background-color:#fcc2d7"></li>
        <li data-value="#faa2c1" style="background-color:#faa2c1"></li>
        <li data-value="#f783ac" style="background-color:#f783ac"></li>
        <li data-value="#f06595" style="background-color:#f06595"></li>
        <li class="on" data-value="#e64980" style="background-color:#e64980"></li>
        <li data-value="#d6336c" style="background-color:#d6336c"></li>
        <li data-value="#c2255c" style="background-color:#c2255c"></li>
        <li data-value="#a61e4d" style="background-color:#a61e4d"></li>
        <li data-value="#f8f0fc" style="background-color:#f8f0fc"></li>
        <li data-value="#f3d9fa" style="background-color:#f3d9fa"></li>
        <li data-value="#eebefa" style="background-color:#eebefa"></li>
        <li data-value="#e599f7" style="background-color:#e599f7"></li>
        <li data-value="#da77f2" style="background-color:#da77f2"></li>
        <li data-value="#cc5de8" style="background-color:#cc5de8"></li>
        <li data-value="#be4bdb" style="background-color:#be4bdb"></li>
        <li data-value="#ae3ec9" style="background-color:#ae3ec9"></li>
        <li data-value="#9c36b5" style="background-color:#9c36b5"></li>
        <li data-value="#862e9c" style="background-color:#862e9c"></li>
        <li data-value="#f3f0ff" style="background-color:#f3f0ff"></li>
        <li data-value="#e5dbff" style="background-color:#e5dbff"></li>
        <li data-value="#d0bfff" style="background-color:#d0bfff"></li>
        <li data-value="#b197fc" style="background-color:#b197fc"></li>
        <li data-value="#9775fa" style="background-color:#9775fa"></li>
        <li data-value="#845ef7" style="background-color:#845ef7"></li>
        <li data-value="#7950f2" style="background-color:#7950f2"></li>
        <li data-value="#7048e8" style="background-color:#7048e8"></li>
        <li data-value="#6741d9" style="background-color:#6741d9"></li>
        <li data-value="#5f3dc4" style="background-color:#5f3dc4"></li>
        <li data-value="#edf2ff" style="background-color:#edf2ff"></li>
        <li data-value="#dbe4ff" style="background-color:#dbe4ff"></li>
        <li data-value="#bac8ff" style="background-color:#bac8ff"></li>
        <li data-value="#91a7ff" style="background-color:#91a7ff"></li>
        <li data-value="#748ffc" style="background-color:#748ffc"></li>
        <li data-value="#5c7cfa" style="background-color:#5c7cfa"></li>
        <li data-value="#4c6ef5" style="background-color:#4c6ef5"></li>
        <li data-value="#4263eb" style="background-color:#4263eb"></li>
        <li data-value="#3b5bdb" style="background-color:#3b5bdb"></li>
        <li data-value="#364fc7" style="background-color:#364fc7"></li>
        <li data-value="#e7f5ff" style="background-color:#e7f5ff"></li>
        <li data-value="#d0ebff" style="background-color:#d0ebff"></li>
        <li data-value="#a5d8ff" style="background-color:#a5d8ff"></li>
        <li data-value="#74c0fc" style="background-color:#74c0fc"></li>
        <li data-value="#4dabf7" style="background-color:#4dabf7"></li>
        <li data-value="#339af0" style="background-color:#339af0"></li>
        <li data-value="#228be6" style="background-color:#228be6"></li>
        <li data-value="#1c7ed6" style="background-color:#1c7ed6"></li>
        <li data-value="#1971c2" style="background-color:#1971c2"></li>
        <li data-value="#1864ab" style="background-color:#1864ab"></li>
        <li data-value="#e3fafc" style="background-color:#e3fafc"></li>
        <li data-value="#c5f6fa" style="background-color:#c5f6fa"></li>
        <li data-value="#99e9f2" style="background-color:#99e9f2"></li>
        <li data-value="#66d9e8" style="background-color:#66d9e8"></li>
        <li data-value="#3bc9db" style="background-color:#3bc9db"></li>
        <li data-value="#22b8cf" style="background-color:#22b8cf"></li>
        <li data-value="#15aabf" style="background-color:#15aabf"></li>
        <li data-value="#1098ad" style="background-color:#1098ad"></li>
        <li data-value="#0c8599" style="background-color:#0c8599"></li>
        <li data-value="#0b7285" style="background-color:#0b7285"></li>
        <li data-value="#e6fcf5" style="background-color:#e6fcf5"></li>
        <li data-value="#c3fae8" style="background-color:#c3fae8"></li>
        <li data-value="#96f2d7" style="background-color:#96f2d7"></li>
        <li data-value="#63e6be" style="background-color:#63e6be"></li>
        <li data-value="#38d9a9" style="background-color:#38d9a9"></li>
        <li data-value="#20c997" style="background-color:#20c997"></li>
        <li data-value="#12b886" style="background-color:#12b886"></li>
        <li data-value="#0ca678" style="background-color:#0ca678"></li>
        <li data-value="#099268" style="background-color:#099268"></li>
        <li data-value="#087f5b" style="background-color:#087f5b"></li>
        <li data-value="#ebfbee" style="background-color:#ebfbee"></li>
        <li data-value="#d3f9d8" style="background-color:#d3f9d8"></li>
        <li data-value="#b2f2bb" style="background-color:#b2f2bb"></li>
        <li data-value="#8ce99a" style="background-color:#8ce99a"></li>
        <li data-value="#69db7c" style="background-color:#69db7c"></li>
        <li data-value="#51cf66" style="background-color:#51cf66"></li>
        <li data-value="#40c057" style="background-color:#40c057"></li>
        <li data-value="#37b24d" style="background-color:#37b24d"></li>
        <li data-value="#2f9e44" style="background-color:#2f9e44"></li>
        <li data-value="#2b8a3e" style="background-color:#2b8a3e"></li>
        <li data-value="#f4fce3" style="background-color:#f4fce3"></li>
        <li data-value="#e9fac8" style="background-color:#e9fac8"></li>
        <li data-value="#d8f5a2" style="background-color:#d8f5a2"></li>
        <li data-value="#c0eb75" style="background-color:#c0eb75"></li>
        <li data-value="#a9e34b" style="background-color:#a9e34b"></li>
        <li data-value="#94d82d" style="background-color:#94d82d"></li>
        <li data-value="#82c91e" style="background-color:#82c91e"></li>
        <li data-value="#74b816" style="background-color:#74b816"></li>
        <li data-value="#66a80f" style="background-color:#66a80f"></li>
        <li data-value="#5c940d" style="background-color:#5c940d"></li>
        <li data-value="#fff9db" style="background-color:#fff9db"></li>
        <li data-value="#fff3bf" style="background-color:#fff3bf"></li>
        <li data-value="#ffec99" style="background-color:#ffec99"></li>
        <li data-value="#ffe066" style="background-color:#ffe066"></li>
        <li data-value="#ffd43b" style="background-color:#ffd43b"></li>
        <li data-value="#fcc419" style="background-color:#fcc419"></li>
        <li data-value="#fab005" style="background-color:#fab005"></li>
        <li data-value="#f59f00" style="background-color:#f59f00"></li>
        <li data-value="#f08c00" style="background-color:#f08c00"></li>
        <li data-value="#e67700" style="background-color:#e67700"></li>
        <li data-value="#fff4e6" style="background-color:#fff4e6"></li>
        <li data-value="#ffe8cc" style="background-color:#ffe8cc"></li>
        <li data-value="#ffd8a8" style="background-color:#ffd8a8"></li>
        <li data-value="#ffc078" style="background-color:#ffc078"></li>
        <li data-value="#ffa94d" style="background-color:#ffa94d"></li>
        <li data-value="#ff922b" style="background-color:#ff922b"></li>
        <li data-value="#fd7e14" style="background-color:#fd7e14"></li>
        <li data-value="#f76707" style="background-color:#f76707"></li>
        <li data-value="#e8590c" style="background-color:#e8590c"></li>
        <li data-value="#d9480f" style="background-color:#d9480f"></li>
      </ul>
    </main>
  </section>
</template>
