# Generated by Django 2.1.3 on 2018-11-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('fabricCanvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
