# Generated by Django 2.0.3 on 2018-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricCanvas', '0004_auto_20181115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='data',
            field=models.TextField(),
        ),
    ]
